### ISSUE TITLE
Error after fix for electron (0.1.42)

### ISSUE THREAD

**Issue by msaigla** [espruino/EspruinoTools#148]
```
> espruino -p COM7

Espruino Command-line Tool 0.1.42
-----------------------------------

Connecting to 'COM7'
undefined:55
    } else throw err;
           ^

Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
Emitted 'error' event on MessageBus instance at:
    at EventEmitter.<anonymous> (C:\Users\msaig\OneDrive\progres\evolvector\evolvector_studio\node_modules\dbus-next\lib\bus.js:159:12)
    at EventEmitter.emit (node:events:520:28)
    at Socket.<anonymous> (C:\Users\msaig\OneDrive\progres\evolvector\evolvector_studio\node_modules\dbus-next\lib\connection.js:102:10)
    at Socket.emit (node:events:520:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/dbus/system_bus_socket'
}
```

**Comment by gfwilliams** [comment]
Not sure what's going on here. You're on Windows, but you're using dbus for some reason? Maybe running with verbose would give more info?

**Comment by msaigla** [comment]
I used Windows 11, WIndows PowerShell and Console VSC.
Console code: 
npm install -g espruino
espruino (error)
esproino -h (okey)
espruino -p COM7 (this id error)

**Comment by msaigla** [comment]
npm install -g espruino@0.1.40
espruino (okey)
esproino -h (okey)
espruino -p COM7 (okey)

**Comment by msaigla** [comment]
test win 10:
Espruino Command-line Tool 0.1.42  
-----------------------------------

Connecting to 'COM4'
undefined:55
    } else throw err;
           ^

Error: connect ENOENT /var/run/dbus/system_bus_socket
    at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Emitted 'error' event on MessageBus instance at:
    at EventEmitter.<anonymous> (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\node_modules\dbus-next\lib\bus.js:159:12)
    at EventEmitter.emit (node:events:527:28)
    at Socket.<anonymous> (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\node_modules\dbus-next\lib\connection.js:102:10)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/dbus/system_bus_socket'
}

**Comment by msaigla** [comment]
node.js 16.14.2
Debian
```
evolvector@astra-evolvector:~$ espruino
Espruino Command-line Tool 0.1.42
-----------------------------------

Error: No Ports Found
evolvector@astra-evolvector:~$ espruino -p /dev/ttyACM0
Espruino Command-line Tool 0.1.42
-----------------------------------

Connecting to '/dev/ttyACM0'
Port "/dev/ttyACM0" not found
Unable to connect!
evolvector@astra-evolvector:~$ espruino -p ttyACM0
Espruino Command-line Tool 0.1.42
-----------------------------------

Connecting to 'ttyACM0'
Port "ttyACM0" not found
Unable to connect!
evolvector@astra-evolvector:~$ espruino -p ttyACM
Espruino Command-line Tool 0.1.42
-----------------------------------

Connecting to 'ttyACM'
Port "ttyACM" not found
Unable to connect!

```

**Comment by gfwilliams** [comment]
do `npm install serialport` and it works for me on Debian just fine. When it fails try using `--verbose` to give more info about what's wrong.

On Windows, you could try `npm remove node-ble` and see if that helps? But I'd need the `--verbose` log for more help.

**Comment by msaigla** [comment]
Windows 11  --verbose:
```
espruino -p COM7 --verbose
0.1.42
Espruino Command-line Tool 0.1.42
-----------------------------------

Acorn library not found - you'll need it for compiled code
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/libs/targz.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/libs/utf8.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/libs/esprima/escodegen.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/libs/esprima/esmangle.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/libs/esprima/esprima.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/espruino.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/codeWriter.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/config.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/env.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/flasher.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/flasherESP8266.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/modules.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/notifications.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_chrome_serial.js
No chrome.serial - Chrome Serial disabled
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_chrome_socket.js
No chrome.sockets - Chrome Socket disabled
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_frame.js
serial_frame: Not running in a browser
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_noble.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_node_ble.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_node_serial.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_node_socket.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_websocket_local.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_websocket_relay.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_web_audio.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_web_bluetooth.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_web_serial.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/serial_winnus.js
'winnus' module not found, no Windows Bluetooth Low Energy Error: Cannot find module 'winnus'
Require stack:
- C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js
- C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\bin\espruino-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at eval (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:10:14)
    at eval (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:124:3)
    at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11)
    at loadDir (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:24:7)
    at Object.init (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:82:3)
    at Object.<anonymous> (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\bin\espruino-cli.js:849:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\msaig\\AppData\\Roaming\\npm\\node_modules\\espruino\\index.js',
    'C:\\Users\\msaig\\AppData\\Roaming\\npm\\node_modules\\espruino\\bin\\espruino-cli.js'
  ]
}
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/terminal.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/core/utils.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/assembler.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/boardJSON.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/compiler.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/getGitHub.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/localModules.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/minify.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/pretokenise.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/saveOnSend.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/setTime.js
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/unicode.js
UTF8 Library loaded successfully
Found C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino/plugins/versionChecker.js
Initialising CodeWriter
Initialising Config
Initialising Env
Initialising Flasher
Initialising FlasherESP8266
Initialising Modules
Initialising Notifications
Initialising Serial
  - Initialising Serial Noble Bluetooth LE
  - Initialising Serial Node-ble Bluetooth LE
  - Initialising Serial Node Serial
  - Initialising Serial Node Socket
  - Initialising Serial Web Audio
  - Initialising Serial Web Bluetooth
  - Initialising Serial Web Serial
Initialising Utils
Initialising Status
Initialising Assembler
Initialising BoardJSON
Initialising Compiler
Initialising GetGitHub
Initialising LocalModules
Initialising Minify
Initialising Unicode
Initialising VersionChecker
Initialising CoreModules
Initialising Pretokenise
Initialising SaveOnSend
Initialising SetTime
Connecting to 'COM7'
Noble: getPorts - initialising...
Noble: module couldn't be loaded, no node.js Bluetooth Low Energy
 Error: Cannot find module '@abandonware/noble'
Require stack:
- C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js
- C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\bin\espruino-cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at startNoble (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:64:17)
    at Object.getPorts (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:145:14)
    at eval (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:109:14)
    at Array.forEach (<anonymous>)
    at getPorts (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:107:13)
    at openSerialInternal (eval at loadJS (C:\Users\msaig\AppData\Roaming\npm\node_modules\espruino\index.js:12:11), <anonymous>:154:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\msaig\\AppData\\Roaming\\npm\\node_modules\\espruino\\index.js',
    'C:\\Users\\msaig\\AppData\\Roaming\\npm\\node_modules\\espruino\\bin\\espruino-cli.js'
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'connect',
  address: '/var/run/dbus/system_bus_socket'
}
```

**Comment by gfwilliams** [comment]
logs?

**Comment by msaigla** [comment]
![image_2022_05_30T11_16_42_672Z](https://user-images.githubusercontent.com/28742439/170985489-02911688-8a95-4002-b330-d7bd9d18d1a1.png)
![image_2022_05_30T11_14_38_056Z](https://user-images.githubusercontent.com/28742439/170985496-84acfbe3-7776-466f-93f9-decd42793c68.png)
