### ISSUE TITLE
404 not found during `npm install espruino`

### ISSUE THREAD

**Issue by cowalla** [espruino/EspruinoTools#166]
```
Documents/coda/puck % npm install espruino                                                                                                                                                                                    
npm ERR! code 1
npm ERR! path /Users/connor/Documents/coda/puck/node_modules/wrtc
npm ERR! command failed
npm ERR! command sh -c node scripts/download-prebuilt.js
npm ERR! 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.17.0
npm ERR! node-pre-gyp info using node@20.8.0 | darwin | arm64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Users/connor/Documents/coda/puck/node_modules/wrtc/build/Release/wrtc.node" (not found)
npm ERR! node-pre-gyp http GET https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 404 https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install error 
npm ERR! node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-webrtc.s3.amazonaws.com/wrtc/v0.4.7/Release/darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! stack     at PassThrough.<anonymous> (/Users/connor/Documents/coda/puck/node_modules/node-pre-gyp/lib/install.js:142:27)
npm ERR! node-pre-gyp ERR! stack     at PassThrough.emit (node:events:526:35)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.<anonymous> (/Users/connor/Documents/coda/puck/node_modules/needle/lib/needle.js:538:9)
npm ERR! node-pre-gyp ERR! stack     at Object.onceWrapper (node:events:629:26)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:535:22)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:376:12)
npm ERR! node-pre-gyp ERR! System Darwin 21.6.0
npm ERR! node-pre-gyp ERR! command "/Users/connor/.nvm/versions/node/v20.8.0/bin/node" "/Users/connor/Documents/coda/puck/node_modules/.bin/node-pre-gyp" "install"
npm ERR! node-pre-gyp ERR! cwd /Users/connor/Documents/coda/puck/node_modules/wrtc
npm ERR! node-pre-gyp ERR! node -v v20.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.17.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /Users/connor/.npm/_logs/2023-10-06T23_29_09_547Z-debug-0.log
```

**Comment by cowalla** [comment]
This is an issue with one of the dependencies not being available for M1 silicon. I worked around this issue by selecting an older version of node to use `nvm use 14`.
