### ISSUE TITLE
Can't provide programatically exact baud rate

### ISSUE THREAD

**Issue by strangeworks** [espruino/EspruinoTools#24]
I'm currently making [repo](https://github.com/strangeworks/esp8266-espruino-demo-scripts) with espruino build examples without ide, and found that it is possible to provide build scripts based on this repo. Attempting to provide basic helloworld build I could find where to provide configuration object(if it is exists, of course). 

My build script currently looks like this
```javascript
var esp = require('espruino');
var Promise = require('bluebird');

var port = '/dev/cu.SLAB_USBtoUART';
var filename = './helloworld.js';

new Promise(function(resolve, reject) {
  esp.init(function() {
    resolve(Espruino)
  })
})
.then(function(Espruino) {
  Espruino.Config.BAUD_RATE = "115200"
})
.then(function() {
  esp.sendFile(port, filename, function() {
    esp.expr(port, "save()", function(result) {
      console.log('file hase been uploaded');
      console.log(result);
    })
  })
})

```

I suspect that build script is not working because of incorrect baud rate. In my case it should be 115200 but it seems that there are no such option.

**Comment by gfwilliams** [comment]
What you're doing looks ok - it seems that the issue is that everything gets re-initialised when `sendFile` is called. I've tweaked it now - let me know if it's any better.

**Comment by strangeworks** [comment]
Thank you, seems it's uploading as expected, but I needed to provide an ugly hack to my build script, because currently I'm getting this.

```
undefined:306
    if (!window || !window.location) return false;
         ^

ReferenceError: window is not defined
    at Object.needsHTTPS (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:306:10)
    at Object.init (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:21:43)
    at initModule (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:47:15)
    at eval (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:51:37)
    at eval (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:82:9)
    at _get (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:57:7)
    at Object.loadConfiguration (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:73:5)
    at HTMLDocument.init (eval at loadJS (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/espruino/index.js:9:15), <anonymous>:42:26)
    at fire (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/jquery/dist/jquery.js:3182:31)
    at Object.self.fireWith [as resolveWith] (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/jquery/dist/jquery.js:3312:7)
    at jQuery.extend.ready [as _onTimeout] (/Users/swks/code/esp8266-espruino-demo-scripts/node_modules/jquery/dist/jquery.js:3531:13)
    at Timer.listOnTimeout (timers.js:92:15)
```

https://github.com/strangeworks/esp8266-espruino-demo-scripts/blob/master/build.js#L7 - currently i'm defining global window object as false, and build process is working.

**Comment by gfwilliams** [comment]
Ahh, thanks - so NPM is out of date? Strange - I must have messed up when updating the package - I'll do it again in a few minutes.
