### ISSUE TITLE
gyp error while installing in node on OSX (missing windows.h)

### ISSUE THREAD

**Issue by piovac** [espruino/EspruinoTools#46]
I have node v6.9.1 installed on my mac (running OSX 10.11.6). While I am installing espruino command line tools with `npm install -g espruino` i get the error below. Why is `windows.h` needed?

```
chatwin:~ piovac$ npm install -g espruino
/usr/local/var/nvm/versions/node/v6.9.1/bin/espruino -> /usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/bin/espruino-cli.js

> xpc-connection@0.1.4 install /usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/node_modules/xpc-connection
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/binding/src/XpcConnection.o
../src/XpcConnection.cpp:143:44: warning: 'GetRealNamedProperty' is deprecated
      [-Wdeprecated-declarations]
      Local<Value> propertyValue = object->GetRealNamedProperty(property...
                                           ^
/Users/piovac/.node-gyp/6.9.1/include/node/v8.h:2923:30: note:
      'GetRealNamedProperty' has been explicitly marked deprecated here
                Local<Value> GetRealNamedProperty(Local<String> key));
                             ^
1 warning generated.
  SOLINK_MODULE(target) Release/binding.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

> serialport@4.0.7 install /usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/node_modules/serialport
> node-pre-gyp install --fallback-to-build

[serialport] Success: "/usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/node_modules/serialport/build/Release/serialport.node" is installed via remote

> winnus@0.0.2 install /usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/node_modules/winnus
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/winnus/cpp/winnus.o
../cpp/winnus.cpp:3:9: warning: unknown pragma ignored [-Wunknown-pragmas]
#pragma warning (disable: 4068)
        ^
../cpp/winnus.cpp:10:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 warning and 1 error generated.
make: *** [Release/obj.target/winnus/cpp/winnus.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/var/nvm/versions/node/v6.9.1/bin/node" "/usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/var/nvm/versions/node/v6.9.1/lib/node_modules/espruino/node_modules/winnus
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
/usr/local/var/nvm/versions/node/v6.9.1/lib
└─┬ espruino@0.0.30
  ├── acorn@4.0.4
  ├── es6-shim@0.35.2
  ├─┬ escodegen@1.8.1
  │ ├── esprima@2.7.3
  │ ├── estraverse@1.9.3
  │ ├── esutils@2.0.2
  │ ├─┬ optionator@0.8.2
  │ │ ├── deep-is@0.1.3
  │ │ ├── fast-levenshtein@2.0.5
  │ │ ├── levn@0.3.0
  │ │ ├── prelude-ls@1.1.2
  │ │ ├── type-check@0.3.2
  │ │ └── wordwrap@1.0.0
  │ └─┬ source-map@0.2.0
  │   └── amdefine@1.0.1
  ├─┬ esmangle@1.0.1
  │ ├── escodegen@1.3.3
  │ ├─┬ escope@1.0.3
  │ │ └── estraverse@2.0.0
  │ ├── esprima@1.1.1
  │ ├─┬ esshorten@1.1.1
  │ │ └── estraverse@4.1.1
  │ ├── estraverse@1.5.1
  │ ├── esutils@1.0.0
  │ ├─┬ optionator@0.3.0
  │ │ ├── fast-levenshtein@1.0.7
  │ │ ├── levn@0.2.5
  │ │ └── wordwrap@0.0.3
  │ └── source-map@0.1.43
  ├── esprima@3.1.3
  ├─┬ noble@1.7.0
  │ ├── bplist-parser@0.0.6
  │ ├─┬ debug@2.2.0
  │ │ └── ms@0.7.1
  │ └── xpc-connection@0.1.4
  ├─┬ request@2.79.0
  │ ├── aws-sign2@0.6.0
  │ ├── aws4@1.5.0
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@2.1.2
  │ │ └── asynckit@0.4.0
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├── strip-ansi@3.0.1
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@4.0.1
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.3.1
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.3
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.10.1
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── bcrypt-pbkdf@1.0.0
  │ │   ├─┬ dashdash@1.14.1
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├─┬ getpass@0.1.6
  │ │   │ └── assert-plus@1.0.0
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.14.5
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.13
  │ │ └── mime-db@1.25.0
  │ ├── oauth-sign@0.8.2
  │ ├── qs@6.3.0
  │ ├── stringstream@0.0.5
  │ ├─┬ tough-cookie@2.3.2
  │ │ └── punycode@1.4.1
  │ ├── tunnel-agent@0.4.3
  │ └── uuid@3.0.1
  ├─┬ serialport@4.0.7
  │ ├── bindings@1.2.1
  │ ├─┬ commander@2.9.0
  │ │ └── graceful-readlink@1.0.1
  │ ├─┬ debug@2.5.2
  │ │ └── ms@0.7.2
  │ ├─┬ lie@3.1.0
  │ │ └── immediate@3.0.6
  │ ├── nan@2.5.0
  │ ├─┬ node-pre-gyp@0.6.32
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ ├─┬ nopt@3.0.6
  │ │ │ └── abbrev@1.0.9
  │ │ ├─┬ npmlog@4.0.1
  │ │ │ ├─┬ are-we-there-yet@1.1.2
  │ │ │ │ ├── delegates@1.0.0
  │ │ │ │ └─┬ readable-stream@2.2.2
  │ │ │ │   ├── buffer-shims@1.0.0
  │ │ │ │   ├── core-util-is@1.0.2
  │ │ │ │   ├── inherits@2.0.3
  │ │ │ │   ├── isarray@1.0.0
  │ │ │ │   ├── process-nextick-args@1.0.7
  │ │ │ │   ├── string_decoder@0.10.31
  │ │ │ │   └── util-deprecate@1.0.2
  │ │ │ ├── console-control-strings@1.1.0
  │ │ │ ├─┬ gauge@2.7.2
  │ │ │ │ ├── aproba@1.0.4
  │ │ │ │ ├── has-unicode@2.0.1
  │ │ │ │ ├── object-assign@4.1.0
  │ │ │ │ ├── signal-exit@3.0.2
  │ │ │ │ ├─┬ string-width@1.0.2
  │ │ │ │ │ ├── code-point-at@1.1.0
  │ │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │ │ │ │   └── number-is-nan@1.0.1
  │ │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ │ ├── supports-color@0.2.0
  │ │ │ │ └── wide-align@1.1.0
  │ │ │ └── set-blocking@2.0.0
  │ │ ├─┬ rc@1.1.6
  │ │ │ ├── deep-extend@0.4.1
  │ │ │ ├── ini@1.3.4
  │ │ │ ├── minimist@1.2.0
  │ │ │ └── strip-json-comments@1.0.4
  │ │ ├─┬ request@2.79.0
  │ │ │ ├── aws-sign2@0.6.0
  │ │ │ ├── aws4@1.5.0
  │ │ │ ├── caseless@0.11.0
  │ │ │ ├─┬ combined-stream@1.0.5
  │ │ │ │ └── delayed-stream@1.0.0
  │ │ │ ├── extend@3.0.0
  │ │ │ ├── forever-agent@0.6.1
  │ │ │ ├─┬ form-data@2.1.2
  │ │ │ │ └── asynckit@0.4.0
  │ │ │ ├─┬ har-validator@2.0.6
  │ │ │ │ ├─┬ chalk@1.1.3
  │ │ │ │ │ ├── ansi-styles@2.2.1
  │ │ │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ │ │ └── supports-color@2.0.0
  │ │ │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ │ │ ├── generate-function@2.0.0
  │ │ │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ │ │ └── is-property@1.0.2
  │ │ │ │ │ ├── jsonpointer@4.0.0
  │ │ │ │ │ └── xtend@4.0.1
  │ │ │ │ └─┬ pinkie-promise@2.0.1
  │ │ │ │   └── pinkie@2.0.4
  │ │ │ ├─┬ hawk@3.1.3
  │ │ │ │ ├── boom@2.10.1
  │ │ │ │ ├── cryptiles@2.0.5
  │ │ │ │ ├── hoek@2.16.3
  │ │ │ │ └── sntp@1.0.9
  │ │ │ ├─┬ http-signature@1.1.1
  │ │ │ │ ├── assert-plus@0.2.0
  │ │ │ │ ├─┬ jsprim@1.3.1
  │ │ │ │ │ ├── extsprintf@1.0.2
  │ │ │ │ │ ├── json-schema@0.2.3
  │ │ │ │ │ └── verror@1.3.6
  │ │ │ │ └─┬ sshpk@1.10.1
  │ │ │ │   ├── asn1@0.2.3
  │ │ │ │   ├── assert-plus@1.0.0
  │ │ │ │   ├── bcrypt-pbkdf@1.0.0
  │ │ │ │   ├── dashdash@1.14.1
  │ │ │ │   ├── ecc-jsbn@0.1.1
  │ │ │ │   ├── getpass@0.1.6
  │ │ │ │   ├── jodid25519@1.0.2
  │ │ │ │   ├── jsbn@0.1.0
  │ │ │ │   └── tweetnacl@0.14.4
  │ │ │ ├── is-typedarray@1.0.0
  │ │ │ ├── isstream@0.1.2
  │ │ │ ├── json-stringify-safe@5.0.1
  │ │ │ ├─┬ mime-types@2.1.13
  │ │ │ │ └── mime-db@1.25.0
  │ │ │ ├── oauth-sign@0.8.2
  │ │ │ ├── qs@6.3.0
  │ │ │ ├── stringstream@0.0.5
  │ │ │ ├─┬ tough-cookie@2.3.2
  │ │ │ │ └── punycode@1.4.1
  │ │ │ ├── tunnel-agent@0.4.3
  │ │ │ └── uuid@3.0.1
  │ │ ├─┬ rimraf@2.5.4
  │ │ │ └─┬ glob@7.1.1
  │ │ │   ├── fs.realpath@1.0.0
  │ │ │   ├─┬ inflight@1.0.6
  │ │ │   │ └── wrappy@1.0.2
  │ │ │   ├── inherits@2.0.3
  │ │ │   ├─┬ minimatch@3.0.3
  │ │ │   │ └─┬ brace-expansion@1.1.6
  │ │ │   │   ├── balanced-match@0.4.2
  │ │ │   │   └── concat-map@0.0.1
  │ │ │   ├─┬ once@1.4.0
  │ │ │   │ └── wrappy@1.0.2
  │ │ │   └── path-is-absolute@1.0.1
  │ │ ├── semver@5.3.0
  │ │ ├─┬ tar@2.2.1
  │ │ │ ├── block-stream@0.0.9
  │ │ │ ├─┬ fstream@1.0.10
  │ │ │ │ └── graceful-fs@4.1.11
  │ │ │ └── inherits@2.0.3
  │ │ └─┬ tar-pack@3.3.0
  │ │   ├─┬ debug@2.2.0
  │ │   │ └── ms@0.7.1
  │ │   ├─┬ fstream@1.0.10
  │ │   │ ├── graceful-fs@4.1.11
  │ │   │ └── inherits@2.0.3
  │ │   ├─┬ fstream-ignore@1.0.5
  │ │   │ ├── inherits@2.0.3
  │ │   │ └─┬ minimatch@3.0.3
  │ │   │   └─┬ brace-expansion@1.1.6
  │ │   │     ├── balanced-match@0.4.2
  │ │   │     └── concat-map@0.0.1
  │ │   ├─┬ once@1.3.3
  │ │   │ └── wrappy@1.0.2
  │ │   ├─┬ readable-stream@2.1.5
  │ │   │ ├── buffer-shims@1.0.0
  │ │   │ ├── core-util-is@1.0.2
  │ │   │ ├── inherits@2.0.3
  │ │   │ ├── isarray@1.0.0
  │ │   │ ├── process-nextick-args@1.0.7
  │ │   │ ├── string_decoder@0.10.31
  │ │   │ └── util-deprecate@1.0.2
  │ │   └── uid-number@0.0.6
  │ └─┬ object.assign@4.0.4
  │   ├─┬ define-properties@1.1.2
  │   │ └── foreach@2.0.5
  │   ├── function-bind@1.1.0
  │   └── object-keys@1.0.11
  ├─┬ tar.gz@1.0.5
  │ ├── bluebird@2.11.0
  │ ├─┬ fstream@1.0.10
  │ │ ├── graceful-fs@4.1.11
  │ │ ├── inherits@2.0.3
  │ │ ├─┬ mkdirp@0.5.1
  │ │ │ └── minimist@0.0.8
  │ │ └─┬ rimraf@2.5.4
  │ │   └─┬ glob@7.1.1
  │ │     ├── fs.realpath@1.0.0
  │ │     ├─┬ inflight@1.0.6
  │ │     │ └── wrappy@1.0.2
  │ │     ├─┬ minimatch@3.0.3
  │ │     │ └─┬ brace-expansion@1.1.6
  │ │     │   ├── balanced-match@0.4.2
  │ │     │   └── concat-map@0.0.1
  │ │     ├── once@1.4.0
  │ │     └── path-is-absolute@1.0.1
  │ ├── mout@0.11.1
  │ └─┬ tar@2.2.1
  │   └── block-stream@0.0.9
  └── utf8@2.1.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@^0.5.1 (node_modules/espruino/node_modules/noble/node_modules/bluetooth-hci-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for bluetooth-hci-socket@0.5.1: wanted {"os":"linux,android,win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: winnus@0.0.2 (node_modules/espruino/node_modules/winnus):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: winnus@0.0.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```

**Comment by piovac** [comment]
Problem solved: it just needed to reconfigure and rebuild `nw-gyp` in side the package. Similar issue in `espruino-web-ide`. See fix at <https://github.com/espruino/EspruinoWebIDE/issues/162>

**Comment by gfwilliams** [comment]
Thanks - this error will probably be from `winnus` - an optional dependency for windows 8.1 and greater Bluetooth support. I'm not sure how to make the package fail to install without errors on other platforms though.
