### ISSUE TITLE
winnus does not fail with inactive Bluetooth adapter

### ISSUE THREAD

**Issue by OwenBrotherwood** [espruino/EspruinoTools#57]
Bluetooth adapter is not available to Windows 10 (dedicated to VM machine)
- No error is given with winnus loading

Further tests may involve disabling bluetooth adapter in bios or removing driver
to find a possible PR

```
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_noble.js
'noble' module couldn't be loaded, no node.js Bluetooth Low Energy
 { Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Device.usb.Device.open (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\usb\usb.js:33:7)
    at BluetoothHciSocket.bindUser (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:81:19)
    at BluetoothHciSocket.bindRaw (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\bluetooth-hci-socket\lib\usb.js:28:8)
    at Hci.init (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\hci-socket\hci.js:101:35)
    at NobleBindings.init (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at new Noble (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\lib\noble.js:50:18)
    at Object.<anonymous> (C:\source\repos\github\OwenBrotherwood\EspruinoTools\node_modules\noble\index.js:4:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32) errno: -12 }
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_nodeserial.js
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_socket.js
No chrome.sockets - serial_socket disabled
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_websocket.js
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_web_bluetooth.js
No navigator.bluetooth - Web Bluetooth not enabled
Found C:\source\repos\github\OwenBrotherwood\EspruinoTools/core/serial_winnus.js
```

**Comment by OwenBrotherwood** [comment]
Solution that can be used, for want of a better one.

**winnus.js**

There is no test for DevicePaths as a possible cause

```
exports.getDevices = function() {
  // Merge the 2 sets of data we have
  var names = winnus.getDeviceNames();
  var paths = winnus.getDevicePaths();
  var devices = [];
  if (typeof paths[0] === 'undefined' || array[0] === null) {
    throw new Error("DevicePaths");
  }
```

**serial_winnus.js**

```
(function () {
  if (typeof require === 'undefined') return;
  var winnus = undefined;
  try {
    winnus = require('winnus');
  } catch (e) {
    console.log("'winnus' module not found, no Windows Bluetooth Low Energy", e);
    return;
  }
  console.log("Disable Web Bluetooth as we have Winnus instead");
  Espruino.Core.Serial.NO_WEB_BLUETOOTH = true;

```

**Comment by OwenBrotherwood** [comment]
@gfwilliams the PR is ready (and "signed off") https://github.com/espruino/winnus/pull/4

**Comment by gfwilliams** [comment]
PR was merged, so closing
