### ISSUE TITLE
`Cannot read property 'length' of undefined` in uglifyjs

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoTools#58]
See https://github.com/espruino/Espruino/issues/1078

**Comment by katrotz** [comment]
Not sure if related, but got same error when using javascript template literals

```
TypeError: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Controller.traverse (/usr/local/lib/node_modules/espruino/node_modules/esmangle/node_modules/estraverse/estraverse.js:411:38)
    at Object.traverse (/usr/local/lib/node_modules/espruino/node_modules/esmangle/node_modules/estraverse/estraverse.js:556:27)
    at annotateDirective (/usr/local/lib/node_modules/espruino/node_modules/esmangle/lib/annotate-directive.js:131:16)
    at Object.optimize (/usr/local/lib/node_modules/espruino/node_modules/esmangle/lib/esmangle.js:159:16)
    at obfuscate (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:138:27)
    at minifyCodeEsprima (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:119:18)
    at minify (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:264:23)
    at Array.eval (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:89:7)
    at cb (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:94:15)
    at compileCode (eval at loadJS (/usr/local/lib/node_modules/espruino/index.js:10:10), <anonymous>:104:7)
```

**Comment by gfwilliams** [comment]
Thanks - yes, this seems to be a general lack of ES6 support. There's this PR that might really help actually: https://github.com/espruino/EspruinoTools/pulls

**Comment by gfwilliams** [comment]
Much better after updating uglify
