### ISSUE TITLE
Missing a required 'core' folder, `npx expruino` not functional

### ISSUE THREAD

**Issue by opichals** [espruino/EspruinoTools#95]
The index.js (https://github.com/espruino/EspruinoTools/blob/gh-pages/index.js#L93) tries to scan the 'core' folder but it is missing in the released npm...

The stacktrace
```
Error: ENOENT: no such file or directory, scandir '.../node_modules/espruino/core'
    at Object.fs.readdirSync (fs.js:904:18)
    at loadDir (.../node_modules/espruino/index.js:16:18)
    at Object.init (.../node_modules/espruino/index.js:93:3)
    at Object.<anonymous> (.../node_modules/espruino/bin/espruino-cli.js:776:24)
    at Module._compile (module.js:653:30)
```

The npm tarball contents
```
 npm pack espruino
npm notice 
npm notice 📦  espruino@0.1.24
npm notice === Tarball Contents === 
npm notice 1.2kB  package.json                  
npm notice 1.2kB  configDefaults.json           
npm notice 4.3kB  espruino.js                   
npm notice 6.4kB  index.js                      
npm notice 10.3kB LICENSE                       
npm notice 16.7kB README.md                     
npm notice 29.3kB bin/espruino-cli.js           
npm notice 123B   libs/README.md                
npm notice 37B    libs/rollup/debug-shim.js     
npm notice 1.4kB  libs/rollup/espruino-rollup.js
npm notice 3.1kB  libs/rollup/index.js          
npm notice 718B   libs/rollup/package.json      
npm notice 1.4kB  libs/rollup/rollup.config.js  
npm notice 23.6kB plugins/assembler.js          
npm notice 1.7kB  plugins/boardJSON.js          
npm notice 5.8kB  plugins/compiler.js           
npm notice 1.2kB  plugins/getGitHub.js          
npm notice 4.2kB  plugins/localModules.js       
npm notice 12.8kB plugins/minify.js             
npm notice 3.0kB  plugins/saveOnSend.js         
npm notice 1.2kB  plugins/setTime.js            
npm notice 2.4kB  plugins/unicode.js            
npm notice 3.1kB  plugins/versionChecker.js     
npm notice === Tarball Details === 
npm notice name:          espruino                                
npm notice version:       0.1.24                                  
npm notice filename:      espruino-0.1.24.tgz                     
npm notice package size:  37.3 kB                                 
npm notice unpacked size: 135.0 kB                                
npm notice shasum:        db5f9abb59222de0ad52ef062f253574df92f783
npm notice integrity:     sha512-q7hiFaHjXiPk+[...]Vn9AOOLOgj78Q==
npm notice total files:   23                                      
```

**Comment by gfwilliams** [comment]
Wow, thanks for this. That's a nightmare. Should be fixed now.

I have no idea what set that off - it obviously worked previously so perhaps a newer version of NPM changed the rules it uses to include folders.
